<h2>About Me</h2>
<?php echo $article->draw('alpha'); ?>
<p>Over the past few years, I've accumulated a strong set of skills that crosses multiple disciplines. One of the largest advantages to having such a large skill set to pull from whilst improving other skills is the ability to gain a large "over the top" view of many different platforms. For example, during my time developing VBA macros in the Microsoft Office infrastructure, I gained valuable insight into all the different hooks and interops the Office libraries have to offer. When it came time to implement Office Sharepoint and develop custom applications against it, it became apparent that Sharepoint is structured in such a fashion to transition classical Office developers easily into their environment.</p>
<p>As you may have surmised from the previous, I have a considerable amount of experience in the Microsoft environment. I began to develop using VB, eventually VB.NET, and transitioned from Desktop development into the ASP.NET framework. During my time developing in ASP.NET, the strengths of VB.NET quickly became weaknesses, prompting me to learn C#. Directly after learning C#, there was a massive upswing in C derived languages on both the Web and Desktop front.</p>
<p>C# was an excellent gateway to continue on into other directions, learning JAVA, and even a working knowledge of C++. JAVA became a turning point for me, because it was the first technology to open the door past Microsoft's offerings. I always had an interest in programming for the web after I saw the power of ASP.NET, but was highly discouraged with the split from the Open Web that the .NET Framework forces.</p>
<p>This is around the time I was introduced to PHP; in this programmer's honest opinion, it quite possibly may be the best Web language of them all. How can you not fall in love with the marriage of Object Orientation, beautiful content serving capabilities, interoperability between the OS and the Application... I had found my language of choice.</p>
<p>Sadly, this was a marriage not meant to be. At this time, I was heavily invested in the Microsoft technology stack, and had to stick with it for a while. PHP, however, she is a beautiful mistress. How can you deny her? So, during the time I was to be dilligently implementing all Microsoft technologies, I quietly spent my time investigating how I could get my beloved LAMP setup operational in Windows.</p>
<p>Let me tell you something, this is no easy feat. Apache, MySQL, and PHP all work together phenominally on a Linux box; take them away from that and you have to figure out how to piece them all back together to work how they should. The one major advantage to re-implementing these technologies on an alternate platform is that I had to become very familiar with their proper behaviors before trying to replicate them. Let me tell you, .htaccess is a walk in the park once you have to figure out what each rule can possibly be broken down into, then map them all out in an IIS web.config</p>
<p>I digress. Supposing you came to this website looking for a breakdown of my skills, and not some lengthy story-- read on. You'll find what you're looking for further into the site.</p>
<?php echo $article->draw('omega'); ?>